name: Docs check
on:
  push: { branches: ["**"] }
  pull_request:
jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links in README
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose README.md docs/**/*.md
