name: Build LaTeX PDF

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: >-
            scheme-small
            latexmk
            amsmath
            amsfonts
            amssymb
            mathtools
            geometry
            bm
            booktabs
            enumitem
            hyperref
            textgreek
            algorithm2e
            algorithmicx
            algpseudocode
            float
            xcolor
            etoolbox

      - name: Build PDF
        run: make

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: ozirus_dilemma-pdf
          path: build/*.pdf
